package com.nutrizulia.domain.model

import com.nutrizulia.data.local.entity.SignosVitalesEntity

data class SignosVitales(
    var consultaId: Int,
    val peso: Double,
    val altura: Double,
    val glicemiaBasal: Int?,
    val glicemiaPostprandial: Int?,
    val glicemiaAleatoria: Int?,
    val hemoglobinaGlicosilada: Double?,
    val trigliceridos: Int?,
    val colesterolTotal: Int?,
    val colesterolHdl: Int?,
    val colesterolLdl: Int?,
    val tensionArterial: String?,
    val frecuenciaCardiaca: Int?,
    val pulso: Int?,
    val saturacionOxigeno: Int?,
    val frecuenciaRespiratoria: Int?,
    val temperatura: Double?,
    val circunferenciaBraquial: Double?,
    val circunferenciaCadera: Double?,
    val circunferenciaCintura: Double?,
    val perimetroCefalico: Double?,
    val isEmbarazo: Boolean?,
    val fechaUltimaMenstruacion: String?,
    val semanasGestacion: Int?,
    val pesoPreEmbarazo: Double?,
    val isTetero: Boolean?,
    val tipoLactancia: String?
)

fun SignosVitalesEntity.toDomain() = SignosVitales(
    consultaId = consultaId,
    peso = peso,
    altura = altura,
    glicemiaBasal = glicemiaBasal,
    glicemiaPostprandial = glicemiaPostprandial,
    glicemiaAleatoria = glicemiaAleatoria,
    hemoglobinaGlicosilada = hemoglobinaGlicosilada,
    trigliceridos = trigliceridos,
    colesterolTotal = colesterolTotal,
    colesterolHdl = colesterolHdl,
    colesterolLdl = colesterolLdl,
    tensionArterial = tensionArterial,
    frecuenciaCardiaca = frecuenciaCardiaca,
    pulso = pulso,
    saturacionOxigeno = saturacionOxigeno,
    frecuenciaRespiratoria = frecuenciaRespiratoria,
    temperatura = temperatura,
    circunferenciaBraquial = circunferenciaBraquial,
    circunferenciaCadera = circunferenciaCadera,
    circunferenciaCintura = circunferenciaCintura,
    perimetroCefalico = perimetroCefalico,
    isEmbarazo = isEmbarazo,
    fechaUltimaMenstruacion = fechaUltimaMenstruacion,
    semanasGestacion = semanasGestacion,
    pesoPreEmbarazo = pesoPreEmbarazo,
    isTetero = isTetero,
    tipoLactancia = tipoLactancia
)